apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolldice
  template:
    metadata:
      labels:
        app: rolldice
    spec:
      containers:
      - name: rolldice
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/roll-dice:latest
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://10.172.27.15:4318"  # IP of your SigNoz OTEL Collector
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rolldice
spec:
  selector:
    app: rolldice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
